### ISSUE TITLE
make fails on 2.7 branch

### ISSUE THREAD

**Issue by attish76** [bendmorris/static-python#2]
[static-python-2.7]$ make -f Static.make clean
rm -f Makefile Modules/Setup

[static-python-2.7]$ make -f Static.make
sed -e 's/#*shared*/*static*/g' Modules/Setup.dist \
Modules/Setup [ -d Modules/extras ] || mkdir Modules/extras
python add_builtins.py  array cmath math _struct time _operator _random _collections _heapq itertools _functools _elementtree _pickle _datetime _bisect unicodedata atexit _weakref datetime  -s 
*\* Found existing builtin posix
*\* Found existing builtin errno
*\* Found existing builtin pwd
*\* Found existing builtin _sre
*\* Found existing builtin _codecs
*\* Found existing builtin _weakref
*\* Found existing builtin zipimport
*\* Found existing builtin _symtable
*\* Added array
*\* Added cmath
*\* Added math
*\* Added _struct
*\* Added time
*\* Added _random
*\* Added _collections
*\* Added _heapq
*\* Added itertools
*\* Added _functools
*\* Added _elementtree
*\* Added _pickle
*\* Added datetime
*\* Added _bisect
*\* Added unicodedata
*\* Found existing builtin xxsubtype
*\* Adding atexit...done.
Traceback (most recent call last):
  File "add_builtins.py", line 366, in <module>
    test=args.test
  File "add_builtins.py", line 120, in add_builtins
    raise Exception("*\* Couldn't find module %s" % name)
Exception: *\* Couldn't find module _operator
make: **\* [Modules/Setup] Error 1

**Comment by bendmorris** [comment]
Thanks - what OS are you using, and what's the version of your default `python` installation?

**Comment by attish76** [comment]
Well, it is a python 2.7.3 on fc16, i686..  It is really sounds strange, but the error above is for the first run only...goes fine for the second run.

**Comment by Eiyeron** [comment]
Same here, with a python 2.7.6 on a i686.
